name: Daily Market Analysis
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


on:
  schedule:
    # Runs at 13:30 UTC every day (7:00 PM IST)
    - cron: '0 11 * * 1-5'
  workflow_dispatch: # This allows you to click a "Run workflow" button manually!

permissions:
  contents: write

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create Output Directories
        run: mkdir -p Report/EMAReport

      - name: Run Analysis Scripts
        run: |
          echo "T" | python Scripts/EMA50D.py
          echo "T" | python Scripts/EMA250D.py
          echo "T" | python Scripts/EMA500D.py
          python Scripts/sectoral_ema_analysis.py

      - name: Push to Google Sheets
        env:
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
          GSHEET_CREDS_JSON: ${{ secrets.GSHEET_CREDS_JSON }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python Scripts/push_to_gsheet.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automated Market Report Update: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main    
          # Pull latest changes from the remote main branch to avoid conflicts
            git pull --rebase origin main
    
          # Push the merged changes
            git push origin main
